### ISSUE TITLE
`v1.2.1` seems broken

### ISSUE THREAD

**Issue by cailloumajor** [pfeiferj/vscode-hurl#5]
Since update to `v1.2.1`, the syntax coloring does not work anymore.

In `Extension host (remote)` log of VSCode, I found:

```
2023-07-05 13:57:59.606 [error] RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
	at se (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:6761)
	at k (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:4462)
	at he (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:7991)
	at xe (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:9810)
	at /home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:50479
	at async parserInit (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/out/extension.js:62:18)
```

**Comment by pfeiferj** [comment]
> Since update to `v1.2.1`, the syntax coloring does not work anymore.
> 
> In `Extension host (remote)` log of VSCode, I found:
> 
> ```
> 2023-07-05 13:57:59.606 [error] RuntimeError: abort(Assertion failed: undefined). Build with -s ASSERTIONS=1 for more info.
> 	at se (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:6761)
> 	at k (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:4462)
> 	at he (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:7991)
> 	at xe (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:9810)
> 	at /home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/node_modules/web-tree-sitter/tree-sitter.js:1:50479
> 	at async parserInit (/home/***/.vscode-server/extensions/jacobpfeifer.pfeifer-hurl-1.2.1/out/extension.js:62:18)
> ```

Thanks for creating the issue! A fix is currently being published using v1.2.2.

It was a classic case of "well it worked on my machine." I'll create a separate issue to create a real testing process for releases.
